// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
